config/routes.rb
RailsApn::Application.routes.draw do
  resources :notifications

  resources :devices

  resources :apps

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticated

  def set_current_user(uid)
    session[:user_id] = uid
  end

  def current_user
    session[:user_id].blank? ? nil : User.find(session[:user_id])
  end

  def authenticated
    if(!Rails.env.test?)
      if(!session[:is_admin])
        is_authenticated = false      
        authenticate_or_request_with_http_basic do |username, password|
            if(username == RailsApn::Application.config.auth_username && password == RailsApn::Application.config.auth_password)
              is_authenticated = true
            end
        end
        if(is_authenticated)
          session[:is_admin] = true
        end
      end
    end
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  # GET /apps
  # GET /apps.xml
  def index
    @apps = APN::App.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @apps }
    end
  end

  # GET /apps/1
  # GET /apps/1.xml
  def show
    @app = APN::App.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @app }
    end
  end

  # GET /apps/new
  # GET /apps/new.xml
  def new
    @app = APN::App.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @app }
    end
  end

  # GET /apps/1/edit
  def edit
    @app = APN::App.find(params[:id])
  end

  # POST /apps
  # POST /apps.xml
  def create
    @app = APN::App.new(params[:app])

    respond_to do |format|
      if @app.save
        format.html { redirect_to(app_url(@app), :notice => 'App was successfully created.') }
        format.xml  { render :xml => @app, :status => :created, :location => app_url(@app) }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @app.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /apps/1
  # PUT /apps/1.xml
  def update
    @app = APN::App.find(params[:id])

    respond_to do |format|
      if @app.update_attributes(params[:app])
        format.html { redirect_to(app_url(@app), :notice => 'App was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @app.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.xml
  def destroy
    @app = APN::App.find(params[:id])
    @app.destroy

    respond_to do |format|
      format.html { redirect_to(apps_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  # GET /devices.xml
  def index
    @devices = APN::Device.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.xml
  def show
    @device = APN::Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.xml
  def new
    @device = APN::Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = APN::Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.xml
  def create
    @device = APN::Device.new(params[:device])
    existing = APN::Device.where(:token=>@device.token).first
    @device = existing if(existing)
    respond_to do |format|
      if !@device.new_record? || @device.save
        format.html { redirect_to(device_url(@device), :notice => 'Device was successfully created.') }
        format.xml  { render :xml => @device, :status => :created, :location => device_url(@device) }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @device.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.xml
  def update
    @device = APN::Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to(device_url(@device), :notice => 'Device was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @device.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.xml
  def destroy
    @device = APN::Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to(devices_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  # GET /notifications
  # GET /notifications.xml
  def index
    @notifications = APN::Notification.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @notifications }
    end
  end

  # GET /notifications/1
  # GET /notifications/1.xml
  def show
    @notification = APN::Notification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @notification }
    end
  end

  # GET /notifications/new
  # GET /notifications/new.xml
  def new
    @notification = APN::Notification.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @notification }
    end
  end

  # GET /notifications/1/edit
  def edit
    @notification = APN::Notification.find(params[:id])
  end

  # POST /notifications
  # POST /notifications.xml
  def create
    set_custom_properties  
    @notification = APN::Notification.new(params[:notification])
    respond_to do |format|
      if @notification.save
        format.html { redirect_to(notification_url(@notification), :notice => 'Notification was successfully created.') }
        format.xml  { render :xml => @notification, :status => :created, :location => notification_path(@notification) }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @notification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notifications/1
  # PUT /notifications/1.xml
  def update
    @notification = APN::Notification.find(params[:id])
    set_custom_properties
    respond_to do |format|
      if @notification.update_attributes(params[:notification])
        format.html { redirect_to(notification_url(@notification), :notice => 'Notification was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @notification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.xml
  def destroy
    @notification = APN::Notification.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to(notifications_url) }
      format.xml  { head :ok }
    end
  end
  
  protected
  def set_custom_properties
    if(params[:notification])
      if(!params[:notification][:custom_properties].blank?)
        if(!params[:notification][:custom_properties].include?("--- !map:ActiveSupport::HashWithIndifferentAccess"))
          params[:notification][:custom_properties] = JSON.parse(params[:notification][:custom_properties])
        end
      else
        params[:notification][:custom_properties] = nil
      end      
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/apps/_form.html.erb
<%= form_for(@app,:as=>:app, :url=>params[:action] == 'edit' ? app_path(@app) : apps_path) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :apn_dev_cert %><br />
    <%= f.text_field :apn_dev_cert %>
  </div>
  <div class="field">
    <%= f.label :apn_prod_cert %><br />
    <%= f.text_field :apn_prod_cert %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', app_path(@app) %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Apn dev cert</th>
    <th>Apn prod cert</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apps.each do |app| %>
  <tr>
    <td><%= app.id %></td>
    <td><%= !app.apn_dev_cert.blank? %></td>
    <td><%= !app.apn_prod_cert.blank? %></td>
    <td><%= link_to 'Show', app_path(app) %></td>
    <td><%= link_to 'Edit', edit_app_path(app) %></td>
    <td><%= link_to 'Destroy', app_path(app), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>ID:</b>
  <%= @app.id %>
</p>

<p>
  <b>Apn dev cert:</b>
  <%= !@app.apn_dev_cert.blank? %>
</p>

<p>
  <b>Apn prod cert:</b>
  <%= !@app.apn_prod_cert.blank? %>
</p>


<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>

app/views/devices/_form.html.erb
<%= form_for(@device,:as=>:device,:url=>params[:action] == 'edit' ? device_path(@device) : devices_path) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :app_id %><br />
    <%= f.text_field :app_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', device_url(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Token</th>
    <th>App</th>
    <th>Last registered at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @devices.each do |device| %>
  <tr>
    <td><%= device.id %></td>
    <td><%= device.token %></td>
    <td><%= device.app_id %></td>
    <td><%= device.last_registered_at %></td>
    <td><%= link_to 'Show', device_url(device) %></td>
    <td><%= link_to 'Edit', edit_device_path(device) %></td>
    <td><%= link_to 'Destroy', device_url(device), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Token:</b>
  <%= @device.token %>
</p>

<p>
  <b>App:</b>
  <%= @device.app_id %>
</p>

<p>
  <b>Last registered at:</b>
  <%= @device.last_registered_at %>
</p>


<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApn</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div class='header'>
  <%= link_to 'Applications', apps_path%>&nbsp;|&nbsp;
  <%= link_to 'Devices', devices_path%>&nbsp;|&nbsp;
  <%= link_to 'Notifications', notifications_path%>
<div>
<%= yield %>

</body>
</html>

app/views/notifications/_form.html.erb
<%= form_for(@notification,:as=>:notification,:url=>params[:action] == 'edit' ? notification_path(@notification) : notifications_path) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :device_id %><br />
    <%= f.text_field :device_id %>
  </div>
  <div class="field">
    <%= f.label :errors_nb %><br />
    <%= f.text_field :errors_nb %>
  </div>
  <div class="field">
    <%= f.label :alert %><br />
    <%= f.text_area :alert, :rows=>5 %>
  </div>  
  <div class="field">
    <%= f.label :device_language %><br />
    <%= f.text_field :device_language %>
  </div>
  <div class="field">
    <%= f.label :sound %><br />
    <%= f.text_field :sound %>
  </div>
  <div class="field">
    <%= f.label :badge %><br />
    <%= f.text_field :badge %>
  </div>
  <div class="field">
    <%= f.label :custom_properties %><br />
    <%= f.text_area :custom_properties, :rows=>2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h1>Listing notifications</h1>

<table>
  <tr>
    <th>Device</th>
    <th>Errors nb</th>
    <th>Alert</th>
    <th>Device language</th>
    <th>Sound</th>
    <th>Badge</th>
    <th>Created at</th>
    <th>Sent at</th>
    <th>Custom properties</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notifications.each do |notification| %>
  <tr>
    <td><%= notification.device_id %></td>
    <td><%= notification.errors_nb %></td>
    <td><%= notification.alert %></td>
    <td><%= notification.device_language %></td>
    <td><%= notification.sound %></td>
    <td><%= notification.badge %></td>
    <td><%= notification.created_at %></td>
    <td><%= notification.sent_at %></td>
    <td><%= notification.custom_properties %></td>
    <td><%= link_to 'Show', notification_path(notification) %></td>
    <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
    <td><%= link_to 'Destroy', notification_path(notification), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Device:</b>
  <%= @notification.device_id %>
</p>

<p>
  <b>Errors nb:</b>
  <%= @notification.errors_nb %>
</p>

<p>
  <b>Alert:</b>
  <%= @notification.alert %>
</p>

<p>
  <b>Device language:</b>
  <%= @notification.device_language %>
</p>

<p>
  <b>Sound:</b>
  <%= @notification.sound %>
</p>

<p>
  <b>Badge:</b>
  <%= @notification.badge %>
</p>

<p>
  <b>Created at:</b>
  <%= @notification.created_at %>
</p>

<p>
  <b>Sent at:</b>
  <%= @notification.sent_at %>
</p>

<p>
  <b>Custom properties:</b>
  <%= @notification.custom_properties %>
</p>


<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>